name: Deploy to EC2

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: 16.170.225.54
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd /home/ubuntu/secure-log-system
            git pull origin main
            docker build -t log-system .
            docker stop log-system || true
            docker rm log-system || true
            docker run -d -p 5000:5000 \
              -e AWS_REGION=eu-north-1 \
              -e S3_BUCKET=secure-log-system-bucket \
              -e CW_LOG_GROUP=/secure-log-system \
              -e CW_LOG_STREAM=app-logs \
              --name log-system \
              log-system
